### ISSUE TITLE
Linux hard drive mounts in read-only mode in latest release

### ISSUE THREAD

**Issue by jfdoming** [fnuecke/oc2#103]
As the title says, I'm encountering the following issue during system boot:
![image](https://user-images.githubusercontent.com/9922514/151646471-b82d3116-8525-4b2b-8d65-05dcf7e01cd0.png)
![image](https://user-images.githubusercontent.com/9922514/151646476-591751fd-df99-45e2-80ee-fc289059abb9.png)

I've verified that this issue only occurs in the latest release (it does not occur in release 0.0.8, and release 0.1.0 crashes for me). I tried looking through some of the most recent commits but couldn't find an obvious culprit.

**Comment by jfdoming** [comment]
After some investigation, reverting commit a1217ba819116dd466b1f08aceb043095ba9445a seems to fix the issue at least in local testing. Not sure what change within that commit caused the issue though.

**Comment by rschulman** [comment]
I confirm that this is happening to me as well, FWIW.

**Comment by fnuecke** [comment]
Will look into it, thanks for reporting!
