### ISSUE TITLE
Sedna incompatible with some Java VMs

### ISSUE THREAD

**Issue by lucsoft** [fnuecke/oc2#11]
Under Java 14
[crash-2021-01-10_15.28.51-server.txt](https://github.com/fnuecke/oc2/files/5792726/crash-2021-01-10_15.28.51-server.txt)

Under Java 8
[crash-2021-01-10_15.34.26-server.txt](https://github.com/fnuecke/oc2/files/5792733/crash-2021-01-10_15.34.26-server.txt)

both crash because of java.lang.NoClassDefFoundError: sun/misc/VM

**Comment by fnuecke** [comment]
Yeah, OpenJDK and Java != 8 currently isn't supported. I'm planning to make a compat lib Sedna can use to make it compatible with different VMs, and especially newer Java versions, without having to lose the perf boost the unsafe memory implementation provides.

**Comment by fnuecke** [comment]
Could you please test this with 2c3a592bbcc03dfcbb7692732129cc9a257770d0 or newer? Did a quick test with Adopt 15 on Windows and that worked. But the Linux JRE/JDK may have small differences, still. Thanks.

**Comment by lucsoft** [comment]
Currently blocked by https://github.com/fnuecke/oc2/issues/17

**Comment by lucsoft** [comment]
Okay using OpenJDK 8 on Linux works
