### ISSUE TITLE
Broken link in the Readme

### ISSUE THREAD

**Issue by lxhom** [fnuecke/oc2#122]
Just noticed that the Network Card example link in the Readme (https://github.com/fnuecke/oc2/blob/1.18-forge/src/main/java/li/cil/oc2/common/bus/device/item/NetworkInterfaceCardItemDevice.java) 404s, I think this is the correct link: https://github.com/fnuecke/oc2/tree/1.18-forge/src/main/java/li/cil/oc2/common/item/NetworkInterfaceCardItem.java

**Comment by lxhom** [comment]
(Sorry for not tagging the issue correctly, the mobile site won't let me assign a tag for some reason)

**Comment by fnuecke** [comment]
Thanks, will fix!
