### ISSUE TITLE
Support changing pitch & volume with the sound card

### ISSUE THREAD

**Issue by man-of-eel** [fnuecke/oc2#126]
You should be able to play sounds of different pitches and volume with the soundcard, maybe as a second and third argument to the playSound command.

**Comment by lxhom** [comment]
Should be pretty easy to implement, [there are already parameters for that, they're just set to 1](https://github.com/fnuecke/oc2/blob/1.18-forge/src/main/java/li/cil/oc2/common/bus/device/rpc/item/SoundCardItemDevice.java#L59) so adding an argument looks viable
