### ISSUE TITLE
[Enhancement] Add VR goggles

### ISSUE THREAD

**Issue by devBob027** [fnuecke/oc2#134]
A computer you can wear on your head. It would be nice if it also captured your mouse movement.

**Comment by AshtonSnapp** [comment]
So, something like [the AR Goggles from Advanced Peripherals](https://docs.srendi.de/1.18/items/ar_goggles/) but operating as an independent computer?

**Comment by CoolCat467** [comment]
That would be cool, but not sure how it would be used.

**Comment by fnuecke** [comment]
Probably won't add item-based computers, so if anything would be an item companion to a block/card.

That said, while "in-world" rendering could be neat, I don't think I'd have the endurance to maintain that. Maybe at some point in the future once the mod is a little more complete and robust.
