### ISSUE TITLE
Some HLAPI components have a missing ID

### ISSUE THREAD

**Issue by big-lip-bob** [fnuecke/oc2#135]
![image](https://user-images.githubusercontent.com/41026257/154850417-be9ef49d-51e0-453b-9dd9-e453590e869e.png)
There's an inconsistency, for the `robot` and `inventory_operations` component, within their list of capabilities (`typeNames`), they don't have their item/block ID like every other component (as demonstrated by `block_operations`).
This does look like an oversight / bug.

**Comment by fnuecke** [comment]
I can't remember/tell when this may have been fixed, but I can't repro this. If you still can, please let me know.
