### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by ghost** [fnuecke/oc2#143]
Cool mod but texture so SMOOTH and it sucks. Can you add texture choose or make a resourcepack with old styled textures

**Comment by atirutw** [comment]
I like OC2's texture more than original OC. The original mod have this "fake lighting" baked into the textures and it looks weird when them blocks are places on a ground and the bottom part looks super dark.

**Comment by fnuecke** [comment]
Feel free to make a custom texture pack.
