### ISSUE TITLE
Breakage of the world under some circumstances

### ISSUE THREAD

**Issue by Bs0Dd** [fnuecke/oc2#145]
Since the beginning of using the mod, I have encountered a situation several times when the server part suddenly seems to “hang”. When you try to save the world, the game hangs completely, and the next time you load the world, the "hang" occurs immediately. The situation is corrected only by cleaning the "oc2-blobs" folder. There is probably a glitch somewhere, causing an invalid blob to form, and this leads to a "hang".

![1](https://i.imgur.com/gUxiSHB.png)

Glitched world: [OneDrive](https://elektronikzgora-my.sharepoint.com/:u:/g/personal/vzadorozhkin_elektronik_zgora_pl/Ebt1j_Rb2MdOqLZOGWSs5qYBxoMK8cNUoYtt279HTuV31g?e=Xdfqh6)

**Comment by fnuecke** [comment]
Thanks for that save, that helped a lot! Was a bad check in the virtio device implementation, fixed in the next version.
