### ISSUE TITLE
[BUG] Projector screen sometimes render over things

### ISSUE THREAD

**Issue by Shazuli** [fnuecke/oc2#149]
***Hi***

The Projector image is sometimes rendered over some things (transparent blocks) and the cable render:

(Text should be darker)
![2022-03-11_19 37 21](https://user-images.githubusercontent.com/9884180/157931797-f93e3986-3113-4263-b422-f867bb1387ab.png)
(The text is still visible through the cable)
![2022-03-11_19 24 24](https://user-images.githubusercontent.com/9884180/157931810-a59f3830-a0c1-4a6a-9d23-14f1877b1bc7.png)

**Comment by atirutw** [comment]
I think the second image is rendered right since...... oh nevermind.

**Comment by fnuecke** [comment]
Is this using regular or fabulous rendering?
Are you using any mods that tweak rendering (optifine, phosphor, ...)?

**Comment by Shazuli** [comment]
@fnuecke JEI, Markdown manual, OCII and Sedna. Running on Fancy Graphics. Just a bare-bone pack.

**Comment by Shazuli** [comment]
Although testing it just now in *Fabulous!* Graphics makes the cable render correctly. Not completely sure about the glass though, I guess I was expecting a more clear colour difference. The text is definitely a little bit darker when looking through the glass, just not as much as expected compared to the landscape to the side in the image.

**Comment by fnuecke** [comment]
This should be fixed in the most recent released, it uses the new rendering event for more stable ordering of rendering stuff. If it isn't fixed, please let me know.
