### ISSUE TITLE
[Feature request] portable computers?

### ISSUE THREAD

**Issue by Ai-Kiwi** [fnuecke/oc2#162]
a way to have something like phones or pocket computer (cc twaeked/computercraft).

**Comment by IpsumCapra** [comment]
The original OpenComputers features tablets, I also believe they would make a great addition. The idea of different form factors with different costs does seem like an interesting idea though. I for one would really enjoy creating smartphones using a device with a more suitable formfactor. 
Would creating player portable emulators be possible using the current codebase?

**Comment by IpsumCapra** [comment]
It would perhaps be better to move this to the discussions page, seeing as it is not an issue, but a feature request.

**Comment by fnuecke** [comment]
I currently don't plan on adding portable (item-based) computers, I'm afraid. If someone wanted to do this as an addon, I'd be happy to make API adjustments where necessary and reasonable, though.
