### ISSUE TITLE
Plain computer missing from JEI

### ISSUE THREAD

**Issue by Hawk777** [fnuecke/oc2#163]
When I use the recipe in the JSON file in the repo, I can successfully craft a computer. However, it does not show up in JEI. There are two computers in JEI, one labelled “computer” and one labelled “preconfigured computer”, but neither displays a recipe. The “computer” is not empty, it contains a Linux Flash, which I assume is why it doesn’t show a recipe. But the completely empty computer isn’t present in JEI at all. Given that recipes are also not shown in the handbook, it’s pretty difficult to discover.

OC2 0.1.6+5d0bd81

**Comment by fnuecke** [comment]
The one with the Flash in it should be the crafted one; probably a derp in my JEI integration, will look into it.

**Comment by dhasial** [comment]
I'm sorry to comment on this closed issue, but the bug seems to still be an issue in the v0.1.8 release found on Curseforge. No recipe in JEI for either the "Computer", "Preconfigured Computer", or the "Robot".

**Comment by Hawk777** [comment]
@dhasial it was fixed since 0.1.8, so the fix has been implemented but not released yet (assuming the `1.18.2-forge/0.1.8` tag is accurately placed).
