### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by sqpp** [fnuecke/oc2#166]
Is 1.18.2 expected anytime soon?

As well, do you plan to release Fabric support?

**Comment by fnuecke** [comment]
I've finally finished Elden Ring, so I'm planning to look into the 1.18.2 upgrade soon.

As for fabric, someone requested a 1.18 fabric branch, though I have no idea how far along they are. I personally am not planning to maintain the mod for multiple loaders, don't have the energy and time for that.
