### ISSUE TITLE
ram counted wrong

### ISSUE THREAD

**Issue by ghost** [fnuecke/oc2#169]
I put in 4 sticks of 8 megabytes ram but the total is 19 megs?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/78849100/162587140-f5dbf6b2-fa1b-485a-ae9c-b44f9384a9eb.png)
![image](https://user-images.githubusercontent.com/78849100/162587171-79995934-a690-47d9-92fe-cb78823d3b0c.png)
Forgot to add images

**Comment by samuelh2005** [comment]
Maybe a limitation in the Linux version?

**Comment by spike11302000** [comment]
the linux kernel reserves 10-20 mb of ram for io buffers and kernel memory,
i think you can tune the kernel config to reduce the memory used by the kernel but i haven't tried any of that so i don't know how much can be saved
