### ISSUE TITLE
[Question] How I can install external programs from my Real pc to hard drive?

### ISSUE THREAD

**Issue by ghost** [fnuecke/oc2#174]
How?

**Comment by spike11302000** [comment]
you need to compile programs with riscv-musl and use the io card to transfer the programs to the computer

**Comment by ghost** [comment]
> you need to compile programs with riscv-musl and use the io card to transfer the programs to the computer

I have reiskv build, but how i can transfer it?

**Comment by spike11302000** [comment]
look in the guide and it tells you how to use the filesystem io card
