### ISSUE TITLE
[Forge 1.18.2] Crash on startup

### ISSUE THREAD

**Issue by Archilyte** [fnuecke/oc2#176]
Here is the [log](https://gist.github.com/Archilyte/7d66925a4c799a8ff1bb2620f7ed311d) (it didn't generate a crash log)

The issue was fixed upon removing this mod.

**Comment by CoolCat467** [comment]
That is the server log, not the client log. Server log with just a quick skim through, nothing appears too out of the ordinary. A few errors here and there, but nothing major. The client side log would be more useful. The server side simply sees that the client disconnected.

**Comment by fnuecke** [comment]
If you can reproduce this and have a client log (crashlog), please reopen with these logs.
