### ISSUE TITLE
How to use projector?

### ISSUE THREAD

**Issue by mckuhei** [fnuecke/oc2#184]
https://user-images.githubusercontent.com/31839741/163661521-42aefad6-6bbc-4afe-bec4-ad0ece633876.mp4

**Comment by gaaa12wsa** [comment]
where to download sedna mode

**Comment by sqpp** [comment]
I think you missing the connector and the power

**Comment by heipiao233** [comment]
![2022-04-17_02 52 49](https://user-images.githubusercontent.com/81846300/163687823-fece2e97-6d6f-4447-a717-787066416173.png)

**Comment by mckuhei** [comment]
Oh thanks
