### ISSUE TITLE
where to download sedna mode

### ISSUE THREAD

**Issue by gaaa12wsa** [fnuecke/oc2#185]
i couldn't find such a mod where to download it
![image](https://user-images.githubusercontent.com/102327770/163664261-ac333818-dff7-4761-a886-355973470d5f.png)

**Comment by gaaa12wsa** [comment]
pls

**Comment by copygirl** [comment]
[GitHub](https://github.com/fnuecke/SednaMinecraft) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/sedna).

Looking at [dependencies on CurseForge](https://www.curseforge.com/minecraft/mc-mods/oc2/relations/dependencies) can often help resolve such issues.
