### ISSUE TITLE
how to get package managers like packman

### ISSUE THREAD

**Issue by pixel844** [fnuecke/oc2#187]
do you have any idea how to get package managers like packman or wget since i want to install those types of package managers to it

**Comment by spike11302000** [comment]
there is wget but since you dont have access to the real internet you wont be able to download any there, so package managers will not work unless you setup another computer to act as a package server

**Comment by pixel844** [comment]
is there a way to?

> there is wget but since you dont have access to the real internet you wont be able to download any there, so package managers will not work unless you setup another computer to act as a package server

**Comment by spike11302000** [comment]
at the moment there is no way to connect to the internet. the way to get programs on the computers you need to use the io filesystem card to upload programs to the computer

**Comment by davidearlyoung** [comment]
I'm seeing gzip and tar binaries in the /bin directory of the in game OC2 computers Linux file system. Which in theory could be used to work with multiple files through standard archiving filing tools. (just like in real life for Linux administrators.) Download your desirable files/directory unto a real computer. Then archive into a compressed *.tar.gz file on said computer. Then use the in game Import/Export card to transfer the compressed tar file into your in game virtual OC2 computer. Then use in game computer to extract the tarred compressed file. I'm not going to walk anyone through the full details of that. Your on your own for that.

**Comment by atirutw** [comment]
Dependencies are gonna be a huge pain though

**Comment by davidearlyoung** [comment]
That is a really good point. Didn't think of that.

**Comment by spike11302000** [comment]
you also need to make sure you programs and libraries are compile for riscv-musl as well, so it pretty hard to find precompiled binaries for riscv-musl so you need to compile the programs and libraries yourself

**Comment by pixel844** [comment]
> you also need to make sure you programs and libraries are compile for riscv-musl as well, so it pretty hard to find precompiled binaries for riscv-musl so you need to compile the programs and libraries yourself

I hope they will make it have internet support like normal opencomputers someday

**Comment by fnuecke** [comment]
There's been different approaches to add internet connectivity, but both are complex and may either require additional out-of-game setup or may be too complex for the main mod. Assuming something like this becomes readily available, a package manager + repo would still have to be something someone else would have to run, it's not something I'd want to setup and run.
