### ISSUE TITLE
Backport to 1.16.5?

### ISSUE THREAD

**Issue by jtmaston** [fnuecke/oc2#189]
Hey!
Sorry if this is a redundant question, but are there any plans for a backport to 1.16.5? I've managed to build the 1.16.5 branch and everything works, but it's 1k commits behind 1.18, so clearly there's a lot of stuff missing.

Thanks! Very good work, the mod looks great!

**Comment by CoolCat467** [comment]
@jtmaston See discussions tab #89.
Also relevant:
#179, #123, #151, and #154
Basically, I think the general consensus is that 1.18 is being focused on more at the moment, and potentially older versions will be revisited after everything is set in stone for 1.18. I think someone was working on a fabric port too at one point, but nothing's been happening for quite some time as of now as far as I can tell.

@fnuecke I think you should pin an issue so people don't keep making more issues of basically same question.

**Comment by fnuecke** [comment]
Good idea, done and added issue templates.
