### ISSUE TITLE
Random chunks start flashing when the projector is running in 1.18.2

### ISSUE THREAD

**Issue by devBob027** [fnuecke/oc2#192]
When the projector displays stuff it displays fine but chunks start flashing. I'm using optifine and I'm on Linux, can that be the reason?

**Comment by atirutw** [comment]
Are you using other mods? What does the flashing look like?

**Comment by devBob027** [comment]
Modlist is quite long. It's a homebrew modpack:
appleskin-forge-mc1.18-2.4.0.jar
corpse-1.18.2-1.0.1.jar
flywheel-forge-1.18-0.6.2.jar
MouseTweaks-forge-mc1.18-2.21.jar
Quark-3.2-349.jar
AutoRegLib-1.7-53.jar
createaddition-1.18.2-20220419a.jar
hexcasting-0.7.1.jar
NethersDelight-1.18.2-2.2.0.jar
sedna-1.18.2-forge-1.0.13+7355dbe.jar
buildinggadgets-3.13.0-build.5+mc1.18.2.jar
createdeco-1.2.7-1.18.2.jar
ImmersiveEngineering-1.18.2-8.0.1-147.jar
oc2-1.18.2-forge-0.1.7+6a003fc.jar
selene-1.18.2-1.15.1.jar
ChiselsBits-forge-1.18.2-1.2.84-universal.jar
create-mc1.18.2_v0.4.1.jar
jei-1.18.2-9.5.5.174.jar
Patchouli-1.18.2-67.jar
sit-1.18.2-1.3.2.jar
Clumps-forge-1.18.2-8.0.0+8.jar
create-stuff-additions1.18.2_v1.1.5.jar
kotlinforforge-3.2.0-obf.jar
paucal-1.18.2-0.3.4.jar
StorageDrawers-1.18.2-10.2.0.jar
Controlling-forge-1.18.2-9.0+19.jar
FarmersDelight-1.18.2-1.0.4.jar
markdown_manual-1.18.2-forge-1.2.1+59006bb.jar
pneumaticcraft-repressurized-1.18.2-3.1.5-70.jar
supplementaries-1.18.2-1.3.6.jar

Most of these mods don't mess with rendering but they may still mess with rendering. Here is a picture of the flashing. It seems to only happen when i look down more than 55 degrees
![2022-04-24_17 53 25](https://user-images.githubusercontent.com/65817973/164982799-bb644c08-f082-46fa-a3fd-da0dea0d8ff1.png)
![2022-04-24_18 04 10](https://user-images.githubusercontent.com/65817973/164982900-f4c6e240-eaad-4c72-b20d-714991fe8b26.png)

**Comment by atirutw** [comment]
I am tempted to say this is caused by other mods but I haven't touched OC2 in quite a while so I can't confirm

**Comment by CoolCat467** [comment]
Optifine does some odd stuff, and it's closed source. I would use magnesium (port of sodium, great fabric mod) if possible

**Comment by fnuecke** [comment]
Would recommend trying without optifine, I can make no guarantee for compatibility with optifine.
