### ISSUE TITLE
[feature] Overlay filesystem

### ISSUE THREAD

**Issue by Merith-TK** [fnuecke/oc2#193]
I noticed when testing the datapacks, I had two options, 
1) an layer filesysystem, which is automatically put into `/mnt/builtin`, or 2) an `block` filesystem which contains an raw ext2 partition block meant to be another operating system or specialized harddrive, 

why not add an third option that copies itself over the current booted system?

**Comment by Merith-TK** [comment]
I also noticed that when using an custom layer package, it overrides the contents that were there in the first place (Lua and python helper libraries) making them just not exist,

**Comment by fnuecke** [comment]
> why not add an third option that copies itself over the current booted system?

This would require either modifying the EXT2 from Lua to copy things into the base image, or some magical way of mounting the overlay fs and then have the base kernel add it as an overlay fs. Both are a little more complex than what I'd be happy with right now.

> I also noticed that when using an custom layer package, it overrides the contents that were there in the first place (Lua and python helper libraries) making them just not exist,

This is intended, to allow patching existing layers, unless I'm misunderstanding.

**Comment by Merith-TK** [comment]
> This is intended, to allow patching existing layers, unless I'm misunderstanding

if you add an file anywhere, everything else vanishes

**Comment by fnuecke** [comment]
Huh, I can't repro that. Is this also happening on the latest version for you? If so, could you re-open this with detailed repro steps (plus ideally the overlay you can repro this with)? Thanks!
