### ISSUE TITLE
Version 1.12.2

### ISSUE THREAD

**Issue by LEAL-original** [fnuecke/oc2#194]
Hello,
I got extasic when I heard about OC2! I still use 1.12.2 due to individual mods compatibility.
Is it possible to port it to 1.12.2?

**Comment by lxhom** [comment]
It *is* possible, but backporting a mod takes a lot of work, and nobody is doing it right now. (see [this comment](https://github.com/fnuecke/oc2/discussions/151#discussioncomment-2515999))

**Comment by lucsoft** [comment]
1.12 is a complete rewrite of the java code. There is so much of a technical change a Backport doesn't make sense.

1.14 could be possible.
But everything before is really not feasible.

**Comment by samuelh2005** [comment]
And the normal open computers exist on 1.12.2

**Comment by fnuecke** [comment]
I won't be backporting this.
