### ISSUE TITLE
how to connect a robot to a computer

### ISSUE THREAD

**Issue by ArtyomKor** [fnuecke/oc2#197]
how to connect a robot to a computer using a network tunnel card?

**Comment by ArtyomKor** [comment]
already connected, just need to remove the network interface card

**Comment by ArtyomKor** [comment]
ok, I figured out the connection, but how to remotely control the robot?

**Comment by CoolCat467** [comment]
You could have program running on both robot and computer controlling that exchanges wireless network data and messages control robot?

**Comment by ArtyomKor** [comment]
> You could have program running on both robot and computer controlling that exchanges wireless network data and messages control robot?

How should I connect to the robot through the program?

**Comment by fnuecke** [comment]
Please use the discussions area for non-bug/feature topics, thanks.
