### ISSUE TITLE
Crash: could not reload Tempad shaders

### ISSUE THREAD

**Issue by zfxstd** [fnuecke/oc2#198]
Hello. 

I tried to install OC2 on ATM7 1.18.2 modpack and i got crash. I attached a crash file. For some reasons its seems like to be not full...

I tried version from curse for 1.18.1 and 0.17 from Github releases. Both with same crash.

[crash-2022-05-09_19.31.13-client.txt](https://github.com/fnuecke/oc2/files/8654113/crash-2022-05-09_19.31.13-client.txt)

**Comment by XFactHD** [comment]
"Could not reload Tempad shaders" is an error from the Tempad mod. Due to a bug in that mod, this crash happens when some other mod causes a loading error. The actual error will be hidden somewhere in the debug.log. To make it easier to find the actual problem, remove Tempad temporarily.

**Comment by zfxstd** [comment]
Without Tempad everything working fine. 

I dont actually have a debug.log, only latest.log, which contains almost identical errors, except some errors with forge register events.

Should i still upload latest.log or should i address this issue to Tempad?

**Comment by XFactHD** [comment]
> I don't actually have a debug.log

I assume you are using CurseForge. They thought it would be a really clever idea to suppress the debug.log and gate it behind a switch in the settings.

> Should i still upload latest.log or should i address this issue to Tempad?

I would suggest opening an issue on the Tempad repository. Before you do that you should get the debug.log though.

**Comment by zfxstd** [comment]
Seem like it was my misstake, i forgot to download sedna and markdown first time. 

With sedna and markdown everything working fine with Tempad and no futher crashes are appear. 

Sorry and thanks! :)
