### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by fnuecke** [fnuecke/oc2#2]
Things need recipes. Wanna keep it simple, let's say max depth of 3. One or two intermediary crafting materials, and that only to avoid conflicts.

**Comment by RGFTheCoder** [comment]
Why hasn't the pr been accepted yet?

**Comment by RGFTheCoder** [comment]
@fnuecke

**Comment by fnuecke** [comment]
Have not had the time to look over it yet; recipes have not been my top priority, but they're moving closer to the top.

**Comment by LAutomate-dev** [comment]
Fan feedback: I would enjoy 3-4 depth crafting recipes that involved _at least_ three essential items (transistor, microchip, arithmetic logic unit for example), as well as the use of low-tier ram in higher-tier ram recipes(not HDDs). In general, I really enjoyed the tiered nature of almost everything in oc1, but if this is for simplicity and inclusion of people newer to the mod, then I understand this decision.
