### ISSUE TITLE
Disk drives/removable media

### ISSUE THREAD

**Issue by fnuecke** [fnuecke/oc2#20]
Investigate if the VirtIO block device driver can handle dynamically changing device sizes.
If so this could serve as a backend for removable media.

If not, either someone will have to add an emulated floppy controller or something, or this probably won't be in the (core) mod.

**Comment by rschulman** [comment]
Am I correct that you're referring to the [linux kernal driver](https://github.com/torvalds/linux/blob/master/drivers/block/virtio_blk.c)?

**Comment by fnuecke** [comment]
Yes, exactly.

**Comment by fnuecke** [comment]
Confirmed the driver is capable of reacting to capacity changes. As such, disk drives and floppies are now implemented using VirtIO block devices.
