### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sug0** [fnuecke/oc2#200]
When running `ld` from the [`riscv64` native toolchain](https://musl.cc/), I get a segmentation fault. I loaded these programs via the datapack mechanism, as a 9pfs overlay.

**Comment by samuelh2005** [comment]
Seems to also have a seg fault with gcc, I wished I could compile C programs with this mod

**Comment by sug0** [comment]
> Seems to also have a seg fault with gcc, I wished I could compile C programs with this mod

Some cross compiled programs work just fine. I've successfully compiled a Scheme interpreter from my x86_64 machine, and it runs fine in oc2's VM.

**Comment by samuelh2005** [comment]
I just cross compiled a c hello world program, with wsl on windows. Used the import/export card to import the a.out, and it runs fine.

**Comment by fnuecke** [comment]
I've created an issue to track the random segfaults in sedna: https://github.com/fnuecke/sedna/issues/12
