### ISSUE TITLE
Capabilities are not registered

### ISSUE THREAD

**Issue by pupnewfster** [fnuecke/oc2#203]
See https://github.com/mekanism/Mekanism/issues/7500#issuecomment-1146647160 for a fuller description but it seems like the class this listener https://github.com/fnuecke/oc2/blob/1.18-forge/src/main/java/li/cil/oc2/common/capabilities/CapabilityRegistry.java#L35  is never registered to the event bus so the listener never gets fired.

**Comment by fnuecke** [comment]
Sorry for the delay, finally had some time to catch up with oc2 stuff. Thanks again for letting me know!
