### ISSUE TITLE
Sedna Linux newbie, need networking help

### ISSUE THREAD

**Issue by sentwayfarer** [fnuecke/oc2#206]
I'm trying to send commands to a robot from a computer using redstone inputs. Any info?

**Comment by CoolCat467** [comment]
I have no experience myself, but as I understand it there is a Lua module that lets you read redstone inputs on the computer, and another one to control robots. Have forever loop to read redstone state and then based off that, move robot as desired.

**Comment by fnuecke** [comment]
As mentioned above, if that's what you meant. If you mean for the robot to read redstone values of adjacent blocks, that's not currently possible. Also consider opening a discussion for non-bug/enhancement topics instead, thanks!
