### ISSUE TITLE
Crashed when placing a cable next to a projector when a bus is already connected.

### ISSUE THREAD

**Issue by Kairi-lol** [fnuecke/oc2#209]
I placed a cable next to a projector when it already had a bus connected and it crashes clients, I removed the projector from the region file and it still crashes regardless if I booted the server with the mod or without. I thankfully had a backup I could roll the region files back to.

(I know I wrote internet but its a bus cable)

![EWEsIylgu0](https://user-images.githubusercontent.com/23045776/174733747-5a00812b-bfd8-4295-9e5d-e2451ee7ccbc.png)

`at TRANSFORMER/oc2@0.1.7/li.cil.oc2.client.renderer.ProjectorDepthRenderer.renderProjectorDepthBuffer(ProjectorDepthRenderer.java:331)
	at TRANSFORMER/oc2@0.1.7/li.cil.oc2.client.renderer.ProjectorDepthRenderer.renderProjectorDepths(ProjectorDepthRenderer.java:246)
	at TRANSFORMER/oc2@0.1.7/li.cil.oc2.client.renderer.ProjectorDepthRenderer.handleRenderLevelLast(ProjectorDepthRenderer.java:181)`

[CLIENT 2022-06-20-1.log](https://github.com/fnuecke/oc2/files/8946466/CLIENT.2022-06-20-1.log)
[server latest.log](https://github.com/fnuecke/oc2/files/8946470/server.latest.log)

**Comment by fnuecke** [comment]
I've added a fix for the potential null in the log; doesn't really explain to me why it would relate to a second cable, so if that happens again in a future version, please re-open with a new log, thanks.
