### ISSUE TITLE
module devices not found

### ISSUE THREAD

**Issue by ArtyomKor** [fnuecke/oc2#221]
**Describe the bug**
module 'devices' not found

**To Reproduce**
1. Singleplayer and multiplayer
4. module 'devices' not found

**Log files**
[latest.log](https://github.com/fnuecke/oc2/files/9148639/latest.log)
[debug.log](https://github.com/fnuecke/oc2/files/9148641/debug.log)

**Expected behavior**
Add devices module

**Screenshots**
![image](https://user-images.githubusercontent.com/89897948/179954205-b408b2f2-215d-453e-af67-8744bdffa222.png)

**Versions (please complete the following information):**
 - Minecraft: [e.g. 1.18.2] 1.18.2
 - Forge: [e.g. 40.0.40] 40.1.68
 - OC2: [e.g. 0.1.7] commit f0c9c7134619d163af8eb5bc6db510e47e6f9a27

**Comment by fnuecke** [comment]
Hmm, looks like it already fails doing some init stuff in startup above.

Does it also happen with a fresh computer?

**Comment by fnuecke** [comment]
Ah, I think the paths may have changed between some sedna version changes; please try grabbing a fresh HDD.
