### ISSUE TITLE
Bus Interface interaction

### ISSUE THREAD

**Issue by Dabraleli** [fnuecke/oc2#27]
Is there any way already implemented? Can't see corresponding lua libraries in /usr, "component" for example. 
I guess this will be reimplemented from scratch? Will it support older API used in mods and scripts or will we need to reimplement them?
Sorry for impatience. Your idea to implement RISC-V emulator is really cool!

**Comment by Dabraleli** [comment]
Ah, found /mnt/data with devices.lua and lsdev.lua, working great. I can see that everything changed. Thank you for your job and good luck with development, unluckily I'm C++ dev, not Java and can't help you probably. Should I close this?

**Comment by fnuecke** [comment]
Yeah, that's how devices will generally be made accessible. And yes, no exact overlap with how OC worked.
I'll write some documentation in time.
If that's all for now, I'll be closing this :)
