### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by thepwds** [fnuecke/oc2#271]
It seems to have not been updated for a year.
I'm just wondering because it seems so cool, but it hasn't been updated for a bit.

**Comment by atirutw** [comment]
See: https://github.com/fnuecke/oc2/issues/253#issuecomment-1336404935

**Comment by thepwds** [comment]
Ah, ok. Thanks!

**Comment by samuelh2005** [comment]
Sangar has started development again. The mod now supports Fabric and NeoForge on 1.21.1 and many bugs have been fixed. Its not yet on CurseForge or Modrinth.

**Comment by emanuele246gi** [comment]
@samuelh2005 did he talk about a possible release for Forge 1.20.1?

**Comment by samuelh2005** [comment]
> [@samuelh2005](https://github.com/samuelh2005) did he talk about a possible release for Forge 1.20.1?

No, it appears it was skipped entirely.

**Comment by fnuecke** [comment]
Yeah, I'll focus on one version to flesh things out and stabilize. After that I'll most likely at least port to newer versions, and *maybe* 1.20.1, depending on how much work that'll turn out too be.

**Comment by emanuele246gi** [comment]
Okay, thank you both for the answer.
