### ISSUE TITLE
1.12.2 Version

### ISSUE THREAD

**Issue by KittenPixel** [fnuecke/oc2#279]
**Idea**
Add 1.12.2 support so we can have all the cool features that this brings on 1.12.2

**Comment by CoolCat467** [comment]
This is a duplicate of https://github.com/fnuecke/oc2/discussions/275

**Comment by KittenPixel** [comment]
Oh.

**Comment by CoolCat467** [comment]
In particular, the pinned issue https://github.com/fnuecke/oc2/issues/220 says that this mod will not be backported  unless someone else is interested in doing it.
