### ISSUE TITLE
Bus interfaces can be attached to the front faces of computers

### ISSUE THREAD

**Issue by abyucel** [fnuecke/oc2#28]
Hey, thanks for your work on this amazing mod.

Just wanted to mention that unlike network connectors, it's possible to attach bus interfaces to the front faces of computers by shift-rightclicking.
I'm not sure whether this is the expected behavior or not:

<img src="https://user-images.githubusercontent.com/72408693/110298157-54278500-8005-11eb-8e5e-911139d65519.png" width="300" height="300">

**Comment by fnuecke** [comment]
Thanks for the feedback! This is a bit of a tricky one. I agree that it feels a little odd like this, with no cable to support the interface. But for the sake of convenience (being able to place down interfaces before placing down cables) I'm inclined to leave it like this.

The cable should not actually connect to the computer (if it does it's a but). Which brings up the point that maybe there should be some visual indication that an interface actually has a device it's connected to... but that's a whole other topic.

I'll leave this open to allow myself to think about this a little longer, and may others will chime in.

**Comment by Emmixis** [comment]
This seems useful in the long run; for when people end up making complex stuff with OC2 in compact spaces. If this were up for vote, I vote against changing it.

**Comment by CoolCat467** [comment]
As do I; Somewhere, somehow, someone might end up using this to do something really cool.

**Comment by fnuecke** [comment]
Yeah, I'm fine with keeping this. The added comfort feels worth the potential weirdness.
