### ISSUE TITLE
Command "reboot" does not function correctly

### ISSUE THREAD

**Issue by Emmixis** [fnuecke/oc2#31]
![image](https://user-images.githubusercontent.com/24935973/114889482-11c24680-9e02-11eb-8a40-539951f019d4.png)

## Reproduction Steps
1. Create any computer of valid configuration, using the **linux** set of fw/hdd
2. Load and log into the computer
3. Run command `reboot`

## Notes
Oddly enough, `poweroff` works as-intended. I've not tested this in Sedna by itself, so I'm unsure where the issue lies, sorry.

**Comment by Bs0Dd** [comment]
I ran sedna-cli and tried to reboot in it, but I got the same error. The problem lies somewhere in Sedna itself.
![Unable to restart system](https://i.imgur.com/Su6DMVK.png)

**Comment by Emmixis** [comment]
Closing, issue lies in repo `sedna`, issue will be created there.
