### ISSUE TITLE
Boot priority

### ISSUE THREAD

**Issue by Bs0Dd** [fnuecke/oc2#32]
Linux hard drive has very little space (about 100 kb), so I needed to attach an additional hard drive. But when I try to boot, I get Kernel panic because the system trying to boot from a non-system disk.
![Kernel panic](https://i.imgur.com/vdDwZ5a.png)

Later, I somehow managed to boot from the main drive and format the second one. But on the next boot I was expecting Kernel panic again. The computer tries to boot from a non-system disk again, it manages to mount it, but since there are no Linux files there, an error occurs.
![Kernel panic 2](https://i.imgur.com/zwihcnb.png)

It turns out that BIOS registers a non-system disk as vda, so it tries to boot Linux from it. I installed a smaller disk and as expected the system detects it as vda.
![Wrong priority](https://i.imgur.com/B0gD1LI.png)

**Comment by Emmixis** [comment]
Confirmed replicable on my end

**Comment by NexusOpen** [comment]
OC2 should combine the storage of additional disks imo

**Comment by nia-e** [comment]
I found a temporary workaround which seems to get around this:
* Kernel panic
* Remove 2nd HDD
* Power on computer
* Power off at login prompt (not necessary, looks like you can use the computer at this stage but the computer needs to be powered off before doing the next step)
* Install 2nd HDD
* Power on
This seems to work for me. However, it seems like anything to do with partitions (messing with `fdisk`, editing `/etc/fstab`, etc.) requires you to do this again sometimes. Also, haven't tested ≥2 8MB HDDs but it should (hopefully) work.

**Comment by Emmixis** [comment]
**Proposed fix:**
Add ability to set "boot device" in computer component UI (where drives are installed), remove ambiguity for boot process.

**Comment by fnuecke** [comment]
This was due to a bug in the way default addresses were computed; all devices of the same type got the same one, so which one went first was random. This should be fixed now, and the first HDD should always be the boot one now.
