### ISSUE TITLE
[BUG] Sedna: Unable to add user to groups after creating user

### ISSUE THREAD

**Issue by nia-e** [fnuecke/oc2#38]
Steps to replicate:
Log in as root
`adduser testuser`
`adduser testuser -G wheel`

Expected result: user is added to group wheel
Actual result: `adduser: user 'testuser' is in use`

Attempted fixes: kill any process owned by `testuser`; listing all running processes `ps` as root revealed none

Edit: further details that may/may not be relevant:
* Build compiled on OpenJDK 8 on Arch Linux, 1.16.5 branch, latest commit as of typing this
* Bug happened in survival; not tested in creative
* Computer contained 4x8MB RAM, 1x8MB HDD with Linux, 1x4MB HDD mounted at /home, Linux flash mem, 1x Redstone card, 1 bus connected to a floppy reader with a disk inserted
* Playing a modpack, Valhesia III with OpenComputers & Sedna .jars added to mods folder

**Comment by t3chn0T33n-zz** [comment]
Shouldn't this be in [fnuecke/sedna](https://github.com/fnuecke/sedna)?

**Comment by nia-e** [comment]
Good point, though I've yet to test the bug in Sedna proper outside of MC. I'll do that sometime tomorrow and move the issue over if needed

**Comment by RGFTheCoder** [comment]
I have the same issue on actual linux I think its intended to just be the second command? (adduser testuser -G wheel)

You can add a group later with: `usermod -a -G examplegroup exampleusername`
You can set the primary group with: `usermod -g groupname username`

Source: https://www.howtogeek.com/50787/add-a-user-to-a-group-or-second-group-on-linux/

**Comment by fnuecke** [comment]
I'm pretty sure this is either a configuration issue or limitation of busybox/buildroot. I'll try to look into this at some point, but if someone else wants to do some digging, that'd be much appreciated.

**Comment by fnuecke** [comment]
Found the busybox config. Will work via `addgroup <username> <groupname>` as of 7797c068fae10999738f26c8cc2779dfb1d2181d.
