### ISSUE TITLE
error importing compressed file from main filesystem (tar.gz)

### ISSUE THREAD

**Issue by DevBennyturtle** [fnuecke/oc2#40]
Hello!
I was trying to import a file from my pc to the oc2 computer that was a zipped file (tar.gz) and at first it said the file was too large so I used 7zip to chop it up into sections to use it, but now I get this error
![error](https://user-images.githubusercontent.com/45775493/119867314-c06ea200-beeb-11eb-81f1-af161987d52b.png)
the file I'm trying to upload is : 
[3data.tar.gz](https://github.com/fnuecke/oc2/files/6555640/3data.tar.gz)
[4data.tar.gz](https://github.com/fnuecke/oc2/files/6555643/4data.tar.gz)
[1data.tar.gz](https://github.com/fnuecke/oc2/files/6555645/1data.tar.gz)
[2data.tar.gz](https://github.com/fnuecke/oc2/files/6555647/2data.tar.gz)
(Ive renamed them from tar.gz.001 .002 .003 .004 to what they are now so github will accept them)
This is not malware, It is the dpkg linux package manager. I want to try to install it on oc2

**Comment by CoolCat467** [comment]
You have dpkg in its entirety rewritten in Lua? Because that's what the command you are trying to run thinks its doing.

**Comment by CoolCat467** [comment]
Plus, you'd have to somehow re-link together the segmented files back together after uploading them, or you'd only be running little segments of code and then it would break.

**Comment by DevBennyturtle** [comment]
Why would a tool to import files only work with lua files? What about binaries? Or just text files or pictures

**Comment by DevBennyturtle** [comment]
Also the only reason I want dpkg is so I can install all the .deb files for Gcc and build essentials so I can compile software other than lua

**Comment by fnuecke** [comment]
Fixed as of c1920c524554d2b16214aeb5bfd82f4b2640d0bd. Thanks for reporting this!
