### ISSUE TITLE
support for OpenCubicChunks infinite world height/depth

### ISSUE THREAD

**Issue by Agrrox** [fnuecke/oc2#42]
Hello, as mc1.17 will support negative elevation values, do you think oc2 could be made compatible with OpenCubicChunks mod which extends infinitely the world height and depth?

Here is a link to the CC project:
https://github.com/OpenCubicChunks/CubicChunks

**Comment by CoolCat467** [comment]
Apparently world height can get up to 1024 or something now, don't quote me on that though.

**Comment by fnuecke** [comment]
I don't know what this would involve, but I'm pretty sure I don't have the time, I'm afraid. If someone wants to make a PR that adds whatever explicit support is needed for this -- in a way that it's still just a *soft* dependency -- that'd be appreciated, though.
