### ISSUE TITLE
Wget command problem.

### ISSUE THREAD

**Issue by rainodus** [fnuecke/oc2#70]
I will try download file from github with wget command:
`wget [adress]`
But it give me an error.
![image](https://user-images.githubusercontent.com/59791772/133895009-92d11ab2-05b1-4328-bfd5-4ff170aba4ea.png)
What can i use an alternative for this or how can i fix this?

**Comment by Bs0Dd** [comment]
Sorry, but there is no Internet card (Network cards is designed for local in-game networks), therefore you can't connect to any online services.
You can use File Import/Export card to exchange files with your real PC.
