### ISSUE TITLE
Bad 'tar' in busybox

### ISSUE THREAD

**Issue by Bs0Dd** [fnuecke/oc2#75]
I have a problem with 'tar' integrated in busybox. When i try to unpack tar.xx archive, tar returns `tar: invalid tar magic`.

![Pic](https://i.imgur.com/b9UipV5.png)

I built tar from sources on gnu.org and its works correctly, so there is something wrong with the busybox version.

**Comment by CoolCat467** [comment]
`invalid tar magic` likely means it thinks file header is invalid. Not certain, but likely. Has this worked with different tar files?

**Comment by Bs0Dd** [comment]
> Has this worked with different tar files?

Yes, i tried to unpack some archives with sources. I can unpack all by custom tar, but standard tar always returns `tar: invalid tar magic`

**Comment by Ktlo** [comment]
It looks like `tar` has no compression features there. I got around it using `gunzip`.

```sh
cat yourarchive.tar.gz | gunzip | tar -x
```

**Comment by fnuecke** [comment]
I'll have to see how much extra disk space enabling that feature would eat. May possibly be something we'll just live with as a quirk.

**Comment by fnuecke** [comment]
Can't find an option to enable this in busybox, so the above is what it is, I'm afraid.

**Comment by fnuecke** [comment]
Found the setting after all, will work as of 7797c068fae10999738f26c8cc2779dfb1d2181d.

**Comment by heipiao233** [comment]
tar -xvfz xxx.tar.gz
