### ISSUE TITLE
Add bigger hard drives

### ISSUE THREAD

**Issue by thanos-the-tank-engine** [fnuecke/oc2#77]
The existing 8MB hard drives don't provide enough space to build a development environment or to try to install another programming language like Python into the vm. it's thus quite difficult to take advantage of the fact that the computer is a full linux system.

**Comment by CoolCat467** [comment]
8MB is a lot of storage for just one item in a minecraft world. In some cases, one hard drive could be taking up more memory than the entire minecraft world without the drive. Now, I agree, having more space to have python and such would be awesome, but from a minecraft server owner's perspective this would be an extreme amount of memory for one item.

**Comment by CoolCat467** [comment]
Now, if there were some sort of builtin configuration option that made it so every player only gets one extremely large hard drive, that might make it feasible. Of course, it should be able to be disabled or changed or something, and it would require major changes to how OC2 works. I don't think it would be easy to stop people from crafting more than one, ie it would be nearly impossible to limit people from crafting it, or another mod's autocrafter(s) crafting more than one or a configured amount per player. The only way I can think of to stop people from crafting more than one would be to make them only craftable from some new type of crafting table, and forcing the item to have NBT data talking about the creator, and making the drive invalid if some other mod edited the NBT data. But all of this would be complicated, and therefore I predict it would be unlikely for any larger drives to ever exist.

**Comment by logan2611** [comment]
Definitely +1 on this. It is very easy to max out the 8MB hard drive. Perhaps in addition to adding a per player limit, maybe there could also be a config option to adjust the size of the HDD tiers.

EDIT: I would also like to add that the default Linux install takes up so much space that you're left with even less space than in OC1

**Comment by copygirl** [comment]
For something like a python interpreter, would it be feasible for the server admin to install them globally, and have it available on all computers by default?

**Comment by logan2611** [comment]
> For something like a python interpreter, would it be feasible for the server admin to install them globally, and have it available on all computers by default?

There is a /mnt/builtin folder in buildroot. I don't see why that couldn't be extended, although in its current implementation these files are baked into the mod.

**Comment by fnuecke** [comment]
I'd rather not inflate sizes of user-controlled disk usage. Ideally some sort of global read-only extensibility would become a thing, as mentioned above. Authoring-wise, I imagine it'd be similar to [the current data-pack system](https://github.com/fnuecke/oc2/tree/1.18-forge/src/main/resources/data/oc2/file_systems), just with support for block devices. Implementation-wise, no concrete plans/concepts yet.

**Comment by Kurtoid** [comment]
> install another programming language like Python

silly question: would micropython work?

**Comment by fnuecke** [comment]
> > install another programming language like Python
> 
> silly question: would micropython work?

micropython is currently part of the default rootfs. And I don't think there's any reason it won't stay.

**Comment by ghost** [comment]
Couldn't you just make a program to make a cloud storage on a different machine and use that?

**Comment by Kurtoid** [comment]
Whoops, I haven't played yet; I guess I should before commenting further.
Thank you!

**Comment by fnuecke** [comment]
I've added support for adding custom disk images, which result in extra variants of the image-backed hard drive (which by default is just the built-in Linux). Info on how to set that up [can be found here](https://github.com/fnuecke/oc2/blob/1.18-forge/src/main/resources/data/oc2/file_systems/README.md). Not sure yet if I'll add a system to cycle/select these regularly, or require people to also add a recipe for those. So for now, by default they'll only be obtainable from the creative tab.

You can use that to throw larger images/disks at your installation. I don't plan on bumping the regular disk sizes, for above mentioned reasons (may lead to unexpectedly massive host disk usage, you can just add more disks into the computer, for regular use [scripting] should be sufficient).

Just keep in mind that these images are copied once initialized to make them read-write. So if you use a 500MB image in 4 computers you'll have 2GB of block storage sitting in your world folder.
