### ISSUE TITLE
How to get size of the terminal?

### ISSUE THREAD

**Issue by MHDtA-dev** [fnuecke/oc2#79]
There is no possible ways to get count of lines or columns in the terminal of the computer. `tput` doesn't work, `stty size` doesn't work, variables `$LINES` and `$COLUMNS` also doesn't work. I tried to get the size in c by using ioctl, but it returns zero. I Can't make any programs for this mod because terminal size is important information for me.

<img width="710" alt="s1" src="https://user-images.githubusercontent.com/56554365/145478544-92cbe064-bed8-4a76-85c5-c61d4a46d962.png">
<img width="710" alt="s2" src="https://user-images.githubusercontent.com/56554365/145478555-4442ebb7-76cc-4de9-bd40-73554244de22.png">
<img width="710" alt="s3" src="https://user-images.githubusercontent.com/56554365/145478560-71c92d67-2f44-419c-a890-c28bdce49d75.png">

**Comment by CoolCat467** [comment]
Apparently this might be a problem with busybox.

**Comment by fnuecke** [comment]
Added `COLUMNS` and `LINES` env vars.

**Comment by CoolCat467** [comment]
Added in 8798f95
