### ISSUE TITLE
Screen doesn't reset on reboot

### ISSUE THREAD

**Issue by lucsoft** [fnuecke/oc2#8]
After a reboot the screen doesn't reset completly 

this can be annoying when the background color wasn't reset correctly 
![image](https://user-images.githubusercontent.com/11093382/104121827-9ef88980-5341-11eb-8ec6-922a09623c54.png)

steps to reproduce:

- cat /bin/false
- reboot the system

**Comment by fnuecke** [comment]
Ah; looked to me until now that OpenSBI cleared it on boot, but I guess it just scrolled by the right amount.
