### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by NathanPeake** [fnuecke/oc2#81]
has this been abandoned. would hope not, one of the best mods.

**Comment by atirutw** [comment]
This is indeed worrying, seeing that the latest commit was made quite a few months ago.

**Comment by fnuecke** [comment]
Not abandoned, just on hiatus due to lack of an overlap of time and energy. I'll get back to it :)

**Comment by atirutw** [comment]
OH right, @NathanPeake. There is a tab for [non-issue discussions](https://github.com/fnuecke/oc2/discussions). You might wanna check it out.

**Comment by NathanPeake** [comment]
> Not abandoned, just on hiatus due to lack of an overlap of time and energy. I'll get back to it :)

Thats good to know
