### ISSUE TITLE
OC2 computer causes server crashes when re-entering computer chunks

### ISSUE THREAD

**Issue by ghost** [fnuecke/oc2#85]
Getting constant server crashes after inserting OC2 into list of mods and building a computer meant to monitor another mod's energy. Crashes happen when re-entering chunks with a computer in it. Removing OC2 from the mods list fixes the issue, meaning that this is indeed an issue relating to OC2.

https://pastebin.com/raw/Qnvs6DkJ

**Comment by Codename-Texas** [comment]
This happens when entering or leaving the computer's chunks, server times out then crashes due to the high tick time.

**Comment by Codename-Texas** [comment]
Removing OC2 from the mods list fixes the issue.

**Comment by CoolCat467** [comment]
It might have something to do with immersive engineering or mekanism. Last think OCII does before the stack trace goes to other mods is `li.cil.oc2.common.bus.device.provider.util.AbstractTileEntityCapabilityDeviceProvider` accepting something.

**Comment by ghost** [comment]
I had a bus connected to Mekanism's energy cube (Although half of the time it was never connected to any computer, and still crashed), could that be related?

**Comment by fnuecke** [comment]
From how I read the trace, probably from capability invalidation triggering device collection, which could attempt accessing unloaded chunks. Fixed that, so hopefully this is no longer an issue.

**Comment by ghost** [comment]
> From how I read the trace, probably from capability invalidation triggering device collection, which could attempt accessing unloaded chunks. Fixed that, so hopefully this is no longer an issue.

Will this be back-ported to the 1.16-forge branch?

**Comment by fnuecke** [comment]
No. I'll focus on one version, at least until there's some non-alpha release.
