### ISSUE TITLE
[Feature request] Pause vms when nobody is online

### ISSUE THREAD

**Issue by CrispyPin** [fnuecke/oc2#97]
It would be nice to have the option to pause all vms when nobody is online since they do have some overhead

**Comment by CoolCat467** [comment]
Yea, but this might cause problems for complex systems if it were implemented

**Comment by fnuecke** [comment]
I share that concern, and am wondering if the more consistent approach wouldn't be to pause the server entirely, when nobody is online? At the very least, this option would default to disabled.

**Comment by atirutw** [comment]
I don't think programs that involve timing & clock stuff would take to
pausing VMs very kindly.

**Comment by phorcys420** [comment]
> I share that concern, and am wondering if the more consistent approach wouldn't be to pause the server entirely, when nobody is online? At the very least, this option would default to disabled.

There could be a broadcast to every VM when no one's online ?
So each VM can handle the action differently (one could shutdown, another one could delete some files and reboot, etc), that would allow up for proper "shutting down" for unnecessary VMs.

**Comment by copygirl** [comment]
Pausing VMs is not uncommon, is it?

**Comment by fnuecke** [comment]
> I don't think programs that involve timing & clock stuff would take to pausing VMs very kindly.

Well, the primary RPC uses real-world time, so the machines would just see a sudden skip in reality. But should survive that just fine.

> There could be a broadcast to every VM when no one's online ?

I don't quite grasp the full scenario yet. Is this to throttle/stop machines for "untrusted" players, or a convenience thing for trusted players/self-hosters? What speaks against keeping computers in chunks that just unload when there's no player nearby?

> Pausing VMs is not uncommon, is it?

Sure. It's not that much of a technical difficulty. I'm just worried about the unexpected side-effects, when just a subset of block entities suddenly start updating, as opposed to all others. Pausing them would make it unreliable to use computers to control other systems (e.g. some reactor where a computer avoids it from overheating/blowing up).

**Comment by phorcys420** [comment]
> I don't quite grasp the full scenario yet. Is this to throttle/stop machines for "untrusted" players, or a convenience thing for trusted players/self-hosters? What speaks against keeping computers in chunks that just unload when there's no player nearby?


just a convenience thing for trusted players/self-hosters really

**Comment by ruifung** [comment]
Personally, I feel like *only* pausing the OC2 VM itself might pose... problems as far as gameplay goes. Especially if said VM was running programs controlling something that can go ***boom*** (read: draconic reactors held at barely stable levels, for example).

Wouldn't it be better to just limit chunkloading instead of having something potentially critical stop working when you log off?

**Comment by atirutw** [comment]
> draconic reactors held at barely stable levels

mfw power is more important than safety

**Comment by ruifung** [comment]
> > draconic reactors held at barely stable levels
> 
> mfw power is more important than safety

Pfft. It's _perfectly_ safe. As long as the control programs are running.

**Comment by atirutw** [comment]
Do you guys even use failsafe for reactors?

**Comment by ruifung** [comment]
> Do you guys even use failsafe for reactors?

Yes. Of course. One can never have too many failsafes in that scenario. But I would rather not have to test those.

And we're kind of derailing the issue discussion...

**Comment by fnuecke** [comment]
Closing this for now, from what I'm seeing in particular when they're idling, computers shouldn't have much impact on TPS.
